name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-the-thing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file BlazerDockerTest/Dockerfile
  
  list-the-files:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Example step to run a command 
      run: ls
    
