name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-the-thing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/docker-login@v1
      with:
        login-server: martintestregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - run: |
        docker build . --file BlazerDockerTest/Dockerfile -t martintestregistry.azurecr.io/blazor-docker-test:${{ github.sha }}
        docker push martintestregistry.azurecr.io/blazor-docker-test:${{ github.sha }}
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: TestGroup
        dns-name-label: blazor-docker-test-instance
        image: martintestregistry.azurecr.io/blazor-docker-test:${{ github.sha }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: blazor-docker-test
        location: 'UK south'
